name: Package
on:
  push:
    tags:
      - v1.*
  workflow_dispatch:
jobs:
  push:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: DKrOSS.DotNet.ProjectTemplates
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-tags: true
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Pack
        run: dotnet pack --configuration Release
      - name: Add NuGet source
        run: dotnet nuget add source --username dkraemer --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github https://nuget.pkg.github.com/dkross/index.json
      - name: Push package
        run: dotnet nuget push bin/Release/DKrOSS.DotNet.ProjectTemplates.*.nupkg --source github
